# This code is part of Qiskit.
#
# (C) Copyright IBM 2018, 2019.
#
# This code is licensed under the Apache License, Version 2.0. You may
# obtain a copy of this license in the LICENSE.txt file in the root directory
# of this source tree or at http://www.apache.org/licenses/LICENSE-2.0.
#
# Any modifications or derivative works of this code must retain this
# copyright notice, and modified files need to carry a notice indicating
# that they have been altered from the originals.

notifications:
  on_success: change
  on_failure: always

cache: pip
os: linux
dist: xenial

language: python
python:
  - "3.6"

env: 
  - DEPENDENCY_BRANCH=$(if [[ "$TRAVIS_BRANCH" == stable* ]]; then echo "stable"; else echo "master"; fi)

before_install:
  # Install Dependencies
  - pip install --upgrade pip setuptools wheel
  - |
    # Download dependencies from master
    if [ "$DEPENDENCY_BRANCH" == "master" ]; then
      # Download github Terra
      wget https://codeload.github.com/Qiskit/qiskit-terra/zip/$DEPENDENCY_BRANCH -O /tmp/qiskit-terra.zip
      unzip /tmp/qiskit-terra.zip -d /tmp/
      # Install local Qiskit Terra
      pip install -e /tmp/qiskit-terra-$DEPENDENCY_BRANCH --progress-bar off
      # Download github Ignis
      wget https://codeload.github.com/Qiskit/qiskit-ignis/zip/$DEPENDENCY_BRANCH -O /tmp/qiskit-ignis.zip
      unzip /tmp/qiskit-ignis.zip -d /tmp/
      # Install local Qiskit Ignis
      pip install -e /tmp/qiskit-ignis-$DEPENDENCY_BRANCH --progress-bar off
      # download Qiskit Aqua and unzip it
      wget https://codeload.github.com/Qiskit/qiskit-aqua/zip/$DEPENDENCY_BRANCH -O /tmp/qiskit-aqua.zip
      unzip /tmp/qiskit-aqua.zip -d /tmp/
      # Install local Qiskit Aqua
      pip install -e /tmp/qiskit-aqua-$DEPENDENCY_BRANCH --progress-bar off
    fi
# Test 
install:
  # install library and dev requirements
  - pip install -U -r requirements-dev.txt --progress-bar off
  - pip install -e $TRAVIS_BUILD_DIR --progress-bar off
script:
  - python -m unittest discover -v test
    